import { Base } from "../types";

export const tokens: Record<string, Base> = {
  burn: {
    Name: "Burn",
    Types: "-",
    Subtypes: "-",
    Pitch: null,
    Text: `Immutable\nAt the end of your turn, you and this token both take 1 damage.`,
    Stability: 1,
    School: ".",
  },
  freeze: {
    Name: "Freeze",
    Types: "-",
    Subtypes: "-",
    Pitch: null,
    Text: `"Immutable\nPitch 3: Break this token."`,
    Stability: 1,
    School: ".",
  },
  home: {
    Name: "Home",
    Types: "Primal",
    Subtypes: "Place",
    Pitch: 0,
    Text: ``,
    Stability: 4,
    School: ".",
  },
  squirrel: {
    Name: "Squirrel",
    Types: "Primal",
    Subtypes: "Summon",
    Pitch: 4,
    Text: ``,
    Stability: 1,
    School: ".",
  },
  shield: {
    Name: "Shield",
    Types: "-",
    Subtypes: "Immutable\nAegis",
    Pitch: null,
    Text: ``,
    Stability: 1,
    School: ".",
  },
  contract: {
    Name: "Contract",
    Types: "Deep",
    Subtypes: "Pact",
    Pitch: null,
    Text: "Immutable\nSearch your reserve for a card and place it under this token.\nWhen contract is broken, add all cards under it to your hand.",
    Stability: 1,
    School: ".",
  },
  research: {
    Name: "Research",
    Types: "Arcane",
    Subtypes: "-",
    Pitch: 2,
    Text: "At the beginning of your turn, draw a card and break this spell.",
    Stability: 1,
    School: ".",
  },
  bury: {
    Name: "Bury",
    Types: "Primal",
    Subtypes: "-",
    Pitch: null,
    Text: "Immutable\nPitch 3: Break this token.",
    Stability: 1,
    School: ".",
  },
};
