export const local = {
  range: "BaseSet!A1:I999",
  majorDimension: "ROWS",
  values: [
    [
      "Name",
      "School",
      "Subtypes",
      "Pitch",
      "Cost",
      "Text",
      "Stability",
      "Rarity",
      "Collector Info",
    ],
    [
      "Devil",
      "Deep",
      "Class",
      "",
      "",
      `At the beginning of the game, make a contract token.
        Your pacts have aegis during your opponent's turn.
        Pitch 6: Make a contract token covering target spell you control or instill a contract covering target spell an opponent controls`,
      "",
      "",
      "",
    ],
    [
      "Tomekeeper",
      "Arcane",
      "Class",
      "",
      "",
      "If you would take damage, you may instead put the top 10 cards of your library on the bottom of your reserve.\u003cbr\u003e\nPitch 4: Create a research token.",
      "",
      "",
      "",
    ],
    [
      "Astrologer",
      "Arcane",
      "Class",
      "",
      "",
      "At any time, you may look at and reorder your reserve.\u003cbr\u003e\nIf you would take damage, you may instead discard the top three cards of your reserve deck. (You may only do so if your reserve has cards in it.)",
      "",
      "",
      "",
    ],
    [
      "Alchemist",
      "Arcane",
      "Class",
      "",
      "",
      "Whenever a spell your opponent casts deals damage to you, prevent that damage and make that many burn tokens.\u003cbr\u003e\nPitch 2: Search your reserve for a potion and add it to your hand.",
      "",
      "",
      "",
    ],

    [
      "Bottled Luck",
      "C:\\Card Stuff\\Arcane.jpg",
      "Potion",
      "0",
      "1",
      "Draw a card.\u003cbr\u003e\nWhen you pitch this card, look at the top two cards of your deck, then put them on the top or bottom in any order.",
      "1",
      "C",
    ],
    [
      "Bottled Problems",
      "C:\\Card Stuff\\Arcane.jpg",
      "Potion",
      "0",
      "1",
      "Deal 1 damage to target token.\u003cbr\u003e\nWhen you pitch Bottled Problems, each player makes a burn token.",
      "1",
      "C",
    ],
    [
      "Breach the Vault",
      "C:\\Card Stuff\\Arcane.jpg",
      "Rite",
      "1",
      "4",
      "Ritual 3 (Create a ritual with three of your spells in play.)\u003cbr\u003e\nAs long as the ritual remains unbroken, play with the top card of your reserve revealed.",
      "4",
      "U",
    ],
    [
      "Calamitous Concoction",
      "C:\\Card Stuff\\Arcane.jpg",
      "Potion",
      "1",
      "4",
      "Toll — Pitch three potions.\nDeal 2 damage to any target, then break one of your spells, then make a burn token, then Instill freeze covering target spell, then make a research token, then deal 2 damage to any target.",
      "1",
      "R",
    ],
    [
      "Counterpoint",
      "C:\\Card Stuff\\Arcane.jpg",
      "Abjuration",
      "2",
      "2",
      "Toll — Reveal the top card of your reserve.\u003cbr\u003e\nSwift\u003cbr\u003e\nBreak target spell and counter its effects if it shares a subtype, cost, pitch value, or stability with the revealed card.",
      "2",
      "C",
    ],
    [
      "Destabilize",
      "C:\\Card Stuff\\Arcane.jpg",
      "Ephemeral Incantation",
      "2",
      "25",
      "You may cast any cards you pitched to cast Destabilize without paying their costs, in any order you choose. For each card with more than 5 Cost played in this way, both players take 1 damage.",
      "0",
      "R",
    ],
    [
      "Emergent Design",
      "C:\\Card Stuff\\Arcane.jpg",
      "Ephemeral",
      "1",
      "2",
      "Toll — Search your reserve for a card.\u003cbr\u003e\nBreak two of your spells other than emergent design. If they have a difference in cost equal to the cost of the revealed spell, cast the revealed spell.",
      "0",
      "C",
    ],
    [
      "Forced my Hand",
      "C:\\Card Stuff\\Arcane.jpg",
      "Abjuration",
      "2",
      "2",
      "Toll — Deal 1 damage to yourself.\u003cbr\u003e\nSwift\u003cbr\u003e\nCounter target effect and break its source spell.",
      "1",
      "U",
    ],
    [
      "Great Beyond",
      "C:\\Card Stuff\\Arcane.jpg",
      "Place",
      "2",
      "10",
      "Pitch 0: Cover Great Beyond with the top card of your reserve. The covering card loses its pitch value.",
      "4",
      "R",
    ],
    [
      "Magic Missiles",
      "C:\\Card Stuff\\Arcane.jpg",
      "Evocation",
      "1",
      "4",
      "Deal 1 damage to up to 3 targets.",
      "1",
      "U",
    ],
    [
      "Obfuscation",
      "C:\\Card Stuff\\Arcane.jpg",
      "Curse",
      "2",
      "3",
      "Place on top of target spell. ",
      "1",
      "C",
    ],
    [
      "Overdose",
      "C:\\Card Stuff\\Arcane.jpg",
      "Potion Evocation",
      "-2",
      "0",
      "When you pitch Overdose, search your graveyard for any number of potions. Deal that much damage to any target.",
      "1",
      "U",
    ],
    [
      "Planar Conjunction",
      "C:\\Card Stuff\\Arcane.jpg",
      "Place",
      "2",
      "4",
      "Whenever Planar Conjunction takes damage discard a card, then draw a card.",
      "5",
      "U",
    ],
    [
      "Pondering Orb",
      "C:\\Card Stuff\\Arcane.jpg",
      "Orb",
      "2",
      "4",
      "At the end of each turn, place the top card of your deck under this card face down.\nWhen Pondering Orb is put into your graveyard, add all cards under it to your hand.",
      "3",
      "U",
    ],
    [
      "Potion of Duplicity",
      "C:\\Card Stuff\\Arcane.jpg",
      "Potion",
      "1",
      "2",
      "Search your deck for any number of cards named Potion of Duplicity and add them to your hand.",
      "1",
      "C",
    ],
    [
      "Potion of Mirrorskin",
      "C:\\Card Stuff\\Arcane.jpg",
      "Potion",
      "1",
      "3",
      "Swift\u003cbr\u003e\nChange the target of an effect to its source.",
      "1",
      "C",
    ],
    [
      "Reorganize",
      "C:\\Card Stuff\\Arcane.jpg",
      "Enchantment",
      "2",
      "2",
      "Draw three cards from the top of your reserve, then put two cards from your hand on top of your reserve.",
      "2",
      "C",
    ],
    [
      "Simple Request",
      "C:\\Card Stuff\\Arcane.jpg",
      "Abjuration",
      "2",
      "3",
      "Swift\u003cbr\u003e\nReturn target spell to its owner's hand and counter its effects.",
      "1",
      "C",
    ],
    [
      "Timestop",
      "C:\\Card Stuff\\Arcane.jpg",
      "Ephemeral Incantation",
      "1",
      "20",
      "Trigger all effects that trigger when you start a turn. You may cast a spell, paying for its costs. Then draw until you have 5 cards in hand and trigger all effects that trigger when you end a turn.",
      "0",
      "R",
    ],
    [
      "Wish",
      "C:\\Card Stuff\\Arcane.jpg",
      "Transmutation",
      "2",
      "3",
      "Search your reserve for a card and add it to your hand.",
      "1",
      "C",
    ],
    [
      "Breach of Contract",
      "C:\\Card Stuff\\Deep.jpg",
      "Evocation",
      "2",
      "3",
      "Target a Pact you control.  Return all cards under it to your hand. You take damage equal to the number of cards recovered in this way at the end of your turn (even if Breach of Contract is out of play.)",
      "1",
      "C",
    ],
    [
      "Closet Skeletons",
      "C:\\Card Stuff\\Deep.jpg",
      "Summon",
      "2",
      "3",
      "Whenever you cast an Evocation, you may break Closet Skeletons. If you do, deal 1 damage to any target.",
      "1",
      "C",
    ],
    [
      "Chthonic Pact",
      "C:\\Card Stuff\\Deep.jpg",
      "Pact",
      "2",
      "7",
      "Search your graveyard for any number of cards, put them under Chthonic Pact, then shuffle them.\u003cbr\u003e\nAt the end of each turn, draw a card from Chthonic Pact. ",
      "5",
      "U",
    ],
    [
      "Deal with the Devil",
      "C:\\Card Stuff\\Deep.jpg",
      "Rite",
      "1",
      "7",
      "Ritual 4 (Create a ritual with four of your spells in play.)\u003cbr\u003e\nAs long as the ritual remains unbroken, at the end of turn, make a contract token.",
      "4",
      "U",
    ],
    [
      "Eldritch Blast",
      "C:\\Card Stuff\\Deep.jpg",
      "Ephemeral Evocation",
      "2",
      "3",
      "Deal 4 damage to any target.",
      "0",
      "C",
    ],
    [
      "Eldritch Pact",
      "C:\\Card Stuff\\Deep.jpg",
      "Pact",
      "2",
      "3",
      "You may place any number of your visible spells face down under Eldritch Pact when you cast it.\u003cbr\u003e\nAt the end of each turn, before you draw, draw a card from Eldritch Pact. ",
      "5",
      "C",
    ],
    [
      "Exsanguinate",
      "C:\\Card Stuff\\Deep.jpg",
      "Curse",
      "2",
      "2",
      "Attach Exsanguinate to target spell. \u003cbr\u003e\nDuring your end step, put a Bleed counter on Exsanguinate. Then if it has more Bleed counters than the covered spell's stability, dispel the spell that this is attached to.",
      "1",
      "C",
    ],
    [
      "Glabrezu",
      "C:\\Card Stuff\\Deep.jpg",
      "Summon",
      "2",
      "10",
      "At the end of each turn, break all spells that cost 3 or less.\u003cbr\u003e\nPitch 6 or deal 1 damage to yourself: Glabrezu deals 3 damage to any target.",
      "4",
      "R",
    ],
    [
      "Heretical Pact",
      "C:\\Card Stuff\\Deep.jpg",
      "Pact",
      "2",
      "6",
      "You may search your deck for any 5 cards. Place these cards face down and shuffled beneath Heretical Pact.\u003cbr\u003e\nDraw one card from Heretical Pact at the start of each turn. If you do not play this card immediately, take 1 damage.",
      "4",
      "U",
    ],
    [
      "Hymn of Horror",
      "C:\\Card Stuff\\Deep.jpg",
      "Evocation Hymn",
      "1",
      "2",
      "Deal 1 damage to any target.\u003cbr\u003e\nWhen this spell is used in a Ritual, trigger its effect",
      "1",
      "C",
    ],
    [
      "Kiss of Death",
      "C:\\Card Stuff\\Deep.jpg",
      "Evocation",
      "1",
      "3",
      "Deal 1 damage to any target.\u003cbr\u003e\nWhen a spell with aegis is dealt damage by Kiss of Death, return this spell to your hand.",
      "1",
      "C",
    ],
    [
      "Larvae from Beyond the Fold",
      "C:\\Card Stuff\\Deep.jpg",
      "Summon",
      "3",
      "11",
      "This card may only start the game in your reserve.\u003cbr\u003e\nPlace all cards in your reserve face down under Larvae from Beyond the Fold.\u003cbr\u003e\nAt the end of your turn, search for and cast a spell from under Larvae from Beyond the Fold without paying its cost.",
      "1",
      "R",
    ],
    [
      "Overwhelming Pact",
      "C:\\Card Stuff\\Deep.jpg",
      "Pact",
      "0",
      "0",
      "Place any number of cards from your deck beneath Overwhelming Pact when it enters the board.\u003cbr\u003e\nThis card's pitch value increases by one for every 4 cards beneath it, up to a maximum of 5 pitch value.",
      "1",
      "U",
    ],
    [
      "Pact of the Hollow God",
      "C:\\Card Stuff\\Deep.jpg",
      "Pact",
      "2",
      "12",
      "When you play Pact of the Hollow God, place your entire reserve under it face-down.\u003cbr\u003e Whenever you deal damage to a spell, draw a card from Pact of the Hollow God.\u003cbr\u003e\nIf Pact of the Hollow God is broken, you lose the game.",
      "3",
      "R",
    ],
    [
      "Pact of the Storm",
      "C:\\Card Stuff\\Deep.jpg",
      "Pact",
      "2",
      "3",
      "Place any number of cards from your hand and up to one card from the top of your reserve face down under this card in any order.\u003cbr\u003e\nPitch 1: Reveal and draw the card directly under this card. That card gains Swift until the end of the next turn.",
      "5",
      "C",
    ],
    [
      "Penta Summon",
      "C:\\Card Stuff\\Deep.jpg",
      "Rite",
      "0",
      "0",
      "Ritual 5. If you do, search your reserve for a summon and cast it. (Create a ritual with five of your spells in play.)",
      "2",
      "R",
    ],
    [
      "Persistent Agony",
      "C:\\Card Stuff\\Deep.jpg",
      "Evocation",
      "1",
      "3",
      "Deal 1 damage to any target.\u003cbr\u003e\nPitch 6: Return Persistent Agony from play to your hand.",
      "1",
      "C",
    ],
    [
      "Ravenous Pact",
      "C:\\Card Stuff\\Deep.jpg",
      "Pact",
      "2",
      "4",
      "Any time you pitch a card, place it face down under Ravenous Pact instead of in your graveyard.\u003cbr\u003e\nWhen Ravenous Pact leaves play, you may return one card of your choice from beneath it into your hand. Then shuffle all cards under it into your deck.",
      "3",
      "U",
    ],
    [
      "Silent Pact",
      "C:\\Card Stuff\\Deep.jpg",
      "Pact",
      "2",
      "4",
      "You may place any number of your visible spells face down and shuffled beneath Silent Pact.\u003cbr\u003e\nWhenever you would draw a card, you may instead draw a card from Silent Pact.",
      "3",
      "U",
    ],
    [
      "Speak with Dead",
      "C:\\Card Stuff\\Deep.jpg",
      "Ephemeral",
      "0",
      "2",
      "Search your graveyard for a card and return it to your hand.",
      "0",
      "C",
    ],
    [
      "Beseech the Hallowed",
      "C:\\Card Stuff\\Divine.jpg",
      "Rite",
      "2",
      "6",
      "Ritual 3. If you do, search your reserve for an incantation and add it to your hand. (Create a ritual with three of your spells in play.)\u003cbr\u003e\nAt the beginning of your turn, if the ritual is unbroken, cast an incantation without paying its costs.\u003cbr\u003e\nWhen the ritual breaks, shuffle all of your invocations into your reserve.",
      "1",
      "U",
    ],
    [
      "Chernobog, God of Rot",
      "C:\\Card Stuff\\Divine.jpg",
      "Incantation Summon",
      "1",
      "20",
      "Break one of your spells: Your opponent reveals and discards cards from the top of their deck until they reveal a summon. You may cast that summon.",
      "4",
      "R",
    ],
    [
      "Ctoggha, Dreamwalker",
      "C:\\Card Stuff\\Divine.jpg",
      "Incantation Summon",
      "1",
      "17",
      "Choose a number.\u003cbr\u003e\nAs long as Ctoggha is in play, your hand size is the chosen number.",
      "7",
      "R",
    ],
    [
      "Divine Intervention",
      "C:\\Card Stuff\\Divine.jpg",
      "Ephemeral",
      "3",
      "1",
      "Swift\u003cbr\u003e\nYour incantations are swift until end of turn.",
      "0",
      "C",
    ],
    [
      "Endless Praises in Your Name",
      "C:\\Card Stuff\\Divine.jpg",
      "Rite",
      "2",
      "5",
      "Ritual X (Create a ritual with any number of your spells in play.)\u003cbr\u003e\nAt the end of turn, if the ritual is unbroken, put a glory counter on each spell that's a part of it, then double its pitch value.",
      "1",
      "U",
    ],
    [
      "Guardian Angel",
      "C:\\Card Stuff\\Divine.jpg",
      "Summon",
      "2",
      "3",
      "Swift\u003cbr\u003e\nPlace on top of one of your spells.",
      "3",
      "C",
    ],
    [
      "Hymn of Healing",
      "C:\\Card Stuff\\Divine.jpg",
      "Hymn",
      "1",
      "2",
      "Gain 1 life if you lost life this turn.\u003cbr\u003e\nWhen this spell is used in a Ritual, trigger its effect.",
      "1",
      "C",
    ],
    [
      "Hymn of Hope",
      "C:\\Card Stuff\\Divine.jpg",
      "Hymn",
      "1",
      "2",
      "Reveal the top card of your deck.\u003cbr\u003e\nWhen this spell is used in a Ritual, trigger its effect.",
      "1",
      "C",
    ],
    [
      "Hymn of Strength",
      "C:\\Card Stuff\\Divine.jpg",
      "Hymn",
      "1",
      "2",
      "Deal 1 damage to a target spell. This damage cannot reduce the spell's stability below 1.\u003cbr\u003e\nWhen this spell is used in a Ritual, trigger its effect.",
      "1",
      "C",
    ],
    [
      "Nethuns, Lord of the Deep",
      "C:\\Card Stuff\\Divine.jpg",
      "Incantation Summon",
      "1",
      "20",
      "Instill freeze on all cards your opponent controls. (Your opponent makes the token.)\u003cbr\u003e\nWhenever a player breaks a freeze token, they take 1 damage.",
      "5",
      "R",
    ],
    [
      "Odious Hymn",
      "C:\\Card Stuff\\Divine.jpg",
      "Hymn",
      "1",
      "2",
      "The opponent discards the top 5 cards of their deck.\u003cbr\u003e\nWhen this spell is used in a Ritual, trigger its effect.",
      "1",
      "C",
    ],
    [
      "Potion of Healing",
      "C:\\Card Stuff\\Divine.jpg",
      "Potion",
      "2",
      "2",
      "Swift\u003cbr\u003e\nGain 1 life.",
      "1",
      "C",
    ],
    [
      "Renew the Soul",
      "C:\\Card Stuff\\Divine.jpg",
      "Rite",
      "2",
      "4",
      "Ritual X (Create a ritual with any number of your spells in play.)\u003cbr\u003e\nAt the end of turn, if the ritual is unbroken, shuffle the top X cards of your graveyard into your deck.",
      "1",
      "U",
    ],
    [
      "Rite of Erasure",
      "C:\\Card Stuff\\Divine.jpg",
      "Rite",
      "2",
      "3",
      "Ritual X (Create a ritual with any number of your spells in play.)\u003cbr\u003e\nAt the end of turn, as long as the ritual is unbroken, put the top X cards of your opponent's deck into their graveyard.",
      "4",
      "U",
    ],
    [
      "Saving Grace",
      "C:\\Card Stuff\\Divine.jpg",
      "Abjuration",
      "2",
      "3",
      "Aegis",
      "4",
      "C",
    ],
    [
      "Shield of Faith",
      "C:\\Card Stuff\\Divine.jpg",
      "Abjuration",
      "2",
      "5",
      "Whenever the opponent chooses a target for their spells, they must target Shield of Faith  if able.",
      "6",
      "U",
    ],
    [
      "Stunning Recovery",
      "C:\\Card Stuff\\Divine.jpg",
      "Transmutation",
      "2",
      "3",
      "Swift\u003cbr\u003e\nCover target spell, and remove all damage from it.\nAt the end of turn, uncover the covered spell.",
      "1",
      "C",
    ],
    [
      "Temple of Summoning",
      "C:\\Card Stuff\\Divine.jpg",
      "Place",
      "3",
      "1",
      "Reveal cards from the top of your deck until you reveal an Incantation. Put the Incantation in your hand and all other revealed cards in your graveyard.",
      "1",
      "C",
    ],
    [
      "Theandrios, Light-Bringer",
      "C:\\Card Stuff\\Divine.jpg",
      "Incantation Summon",
      "1",
      "20",
      "Whenever you draw a card, Instill burn. (Your opponent makes the token.)",
      "7",
      "R",
    ],
    [
      "Zodiac Sacrifice",
      "C:\\Card Stuff\\Divine.jpg",
      "Rite",
      "2",
      "5",
      "Ritual 6 (Create a ritual with six of your spells in play.)\u003cbr\u003e\nAt the end of turn, deal 1 damage to all spells in the ritual. Then, if all spells in the ritual are broken, search your deck for a summon and cast it.",
      "1",
      "U",
    ],
    [
      "Animal Shapes",
      "C:\\Card Stuff\\Primal.jpg",
      "Transmutation",
      "1",
      "8",
      "As long as Animal Shapes is in play, all spell effects become On Howl triggered abilities.\u003cbr\u003e\nPitch 4: Howl. (Whenever you Howl, trigger all On Howl abilities.)",
      "3",
      "R",
    ],
    [
      "Assassin Scorpion",
      "C:\\Card Stuff\\Primal.jpg",
      "Summon",
      "2",
      "10",
      "When this card breaks a spell, Howl. (Whenever you Howl, trigger all On Howl abilities.)\u003cbr\u003e\nPitch 3: Deal 1 damage to any target.\u003cbr\u003e\nOn Howl, Deal 1 damage to any target.",
      "4",
      "R",
    ],
    [
      "Burning Brush",
      "C:\\Card Stuff\\Primal.jpg",
      "Place",
      "2",
      "3",
      "At the end of turn, if a player has no cards in hand, deal 1 damage to them.",
      "1",
      "C",
    ],
    [
      "Curing Caverns",
      "C:\\Card Stuff\\Primal.jpg",
      "Place",
      "2",
      "3",
      "Whenever another one of your spells break, you may return it to your hand. If you do, break Curing Caverns.",
      "1",
      "C",
    ],
    [
      "Deadfall",
      "C:\\Card Stuff\\Primal.jpg",
      "Place",
      "2",
      "3",
      "Swift, Aegis, Feedback (If this spell takes excess damage, the excess is dealt to you.)",
      "2",
      "C",
    ],
    [
      "Field of Poppies",
      "C:\\Card Stuff\\Primal.jpg",
      "Place",
      "2",
      "2",
      "As long as Field of Poppies is in play, spells cost 1 more",
      "3",
      "C",
    ],
    [
      "Find Familiar",
      "C:\\Card Stuff\\Primal.jpg",
      "Summon",
      "2",
      "3",
      "Pitch 3: Deal 1 damage to any target.",
      "4",
      "C",
    ],
    [
      "Flashfreeze",
      "C:\\Card Stuff\\Primal.jpg",
      "Ephemeral Hex",
      "2",
      "1",
      "Choose one:\u003cbr\u003e\n- Make a freeze token covering target spell you control.\u003cbr\u003e\n- Instill freeze covering target spell an opponent control.",
      "0",
      "C",
    ],
    [
      "Flying Monkey",
      "C:\\Card Stuff\\Primal.jpg",
      "Summon",
      "2",
      "3",
      "Swift\u003cbr\u003e\nWhen you play this spell on an opponent's turn or On Howl, deal 1 damage to target spell.\u003cbr\u003e\nPitch 4: Howl. (Whenever you Howl, trigger all On Howl abilities.)",
      "1",
      "C",
    ],
    [
      "Grand Tree",
      "C:\\Card Stuff\\Primal.jpg",
      "Summon",
      "2",
      "3",
      "Pitch 3: Make a Squirrel token. Activate this ability only once per turn.",
      "2",
      "C",
    ],
    [
      "Hatespitter Hearth",
      "C:\\Card Stuff\\Primal.jpg",
      "Place",
      "2",
      "5",
      "At the end of each players turn, deal 1 damage to them.",
      "3",
      "U",
    ],
    [
      "Howling Wind",
      "C:\\Card Stuff\\Primal.jpg",
      "Ephemeral Hex",
      "0",
      "4",
      "Swift\u003cbr\u003e\nInstill two freeze on target spell, then counter its effects. (Your opponent makes the token.)\u003cbr\u003e\nWhen this card is pitched, Howl. (Whenever you Howl, trigger all On Howl abilities.)",
      "0",
      "U",
    ],
    [
      "Ice Age Greatmoth",
      "C:\\Card Stuff\\Primal.jpg",
      "Summon",
      "4",
      "17",
      "When you pitch Ice Age Greatmoth to cast a spell, put that spell into play and make a freeze token covering it instead of casting it.\u003cbr\u003e\nWhenever you break a token, Howl. \u003cbr\u003e\nWhenever your opponent breaks a token, deal 1 damage to any target.\u003cbr\u003e\nOn Howl, Instill freeze covering target spell.",
      "2",
      "R",
    ],
    [
      "Path of Peace",
      "C:\\Card Stuff\\Primal.jpg",
      "Place",
      "3",
      "5",
      "Toll — Make freeze tokens covering three of your spells.\u003cbr\u003e\nAs long as Path of Peace is in play, players cannot lose life.",
      "6",
      "R",
    ],
    [
      "Primeval Grounds",
      "C:\\Card Stuff\\Primal.jpg",
      "Place",
      "2",
      "4",
      "As long as Primeval Grounds is in play, spells in play have Immutable. (You can't pitch immutable spells.)\u003cbr\u003e\nAt the beginning of your turn, break Sacred Grounds.",
      "3",
      "U",
    ],
    [
      "Rat King",
      "C:\\Card Stuff\\Primal.jpg",
      "Summon",
      "2",
      "5",
      "When you pitch more than a card's cost to cast it, Howl. (Whenever you Howl, trigger all On Howl abilities.)\u003cbr\u003e\nOn Howl, The opponent discards a card.",
      "2",
      "U",
    ],
    [
      "Rootbind",
      "C:\\Card Stuff\\Primal.jpg",
      "Curse",
      "2",
      "4",
      "Attach to target spell on the board. Abilities on the attached spell do not trigger until Rootbind is removed.\u003cbr\u003e\nWhen the attached spell leaves the board, discard this card and Howl. (Whenever you Howl, trigger all On Howl abilities.)\u003cbr\u003e\nOn Howl, deal 1 damage to the attached spell.",
      "3",
      "U",
    ],
    [
      "Silent Grove",
      "C:\\Card Stuff\\Primal.jpg",
      "Place",
      "2",
      "3",
      "As long as Silent Grove is in play, if another spell would be dealt exactly 1 damage, prevent that damage.",
      "1",
      "C",
    ],
    [
      "Summon Squirrel",
      "C:\\Card Stuff\\Primal.jpg",
      "Summon",
      "4",
      "0",
      '"A useful friend."',
      "1",
      "C",
    ],
    [
      "Watchful Hound",
      "C:\\Card Stuff\\Primal.jpg",
      "Summon",
      "2",
      "4",
      "When you prevent damage, Howl. (Whenever you Howl, trigger all On Howl abilities.)\u003cbr\u003e\nOn Howl, You may prevent one instance of damage that would be dealt to you.",
      "3",
      "U",
    ],
    [
      "Ancient Cairn",
      "C:\\Card Stuff\\Schooless.jpg",
      "Place",
      "-",
      "2",
      "Immutable (You can't pitch this spell.)\u003cbr\u003e\nAs long as Ancient Cairn is in play, spells cost 1 less.",
      "1",
      "C",
    ],
    [
      "Ancient Conduit",
      "C:\\Card Stuff\\Schooless.jpg",
      "Place",
      "1",
      "3",
      "Aegis, Feedback (If this spell takes excess damage, the excess is dealt to you.)\u003cbr\u003e\nAs long as Ancient Conduit is in play, incantation cost 2 less for each of your spells.",
      "2",
      "C",
    ],
    [
      "Antimagic Field",
      "C:\\Card Stuff\\Schooless.jpg",
      "Place",
      "2",
      "6",
      "Feedback (If this spell takes excess damage, the excess is dealt to you.)\u003cbr\u003e\nAll other spells on the board are Feedback while antimagic field is in play.",
      "1",
      "U",
    ],
    [
      "Aura Compost",
      "C:\\Card Stuff\\Schooless.jpg",
      "Transmutation",
      "2",
      "4",
      "As long as Aura Compost is in play, the pitch value of your spells in play increases by 2.",
      "2",
      "U",
    ],
    [
      "Ax",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral",
      "1",
      "7",
      "Deal 7 damage to any target.",
      "0",
      "U",
    ],
    [
      "Bold Fortune",
      "C:\\Card Stuff\\Schooless.jpg",
      "Enchantment",
      "1",
      "5",
      "At the beginning of your turn, break this spell, then each player discards their hand and draws 7 cards.",
      "1",
      "U",
    ],
    [
      "Counterspell",
      "C:\\Card Stuff\\Schooless.jpg",
      "Abjuration",
      "2",
      "4",
      "Swift\u003cbr\u003e\nCounter target effect and break its source spell.",
      "1",
      "C",
    ],
    [
      "Crown of Madness",
      "C:\\Card Stuff\\Schooless.jpg",
      "Enchantment",
      "-",
      "3",
      "Immutable (You can't pitch this spell.)\u003cbr\u003e\nWhen you would be dealt damage, instead give Crown of Madness to the opponent.\nYour hand size is increased by 1. ",
      "1",
      "C",
    ],
    [
      "Decrepit Crypt",
      "C:\\Card Stuff\\Schooless.jpg",
      "Place",
      "1",
      "2",
      "At the beginning of your turn, Ancient Conduit deals 1 damage to you. \u003cbr\u003e\nAs long as Decrepit Crypt is in play, the first spell you cast each turn costs 2 less.",
      "2",
      "C",
    ],
    [
      "Detonate",
      "C:\\Card Stuff\\Schooless.jpg",
      "Hex Evocation",
      "1",
      "2",
      "Deal 1 damage to any target. If a spell is broken this way, Instill burn. (Your opponent makes the token.)",
      "1",
      "C",
    ],
    [
      "Drink Deep and Descend",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral",
      "0",
      "0",
      "Toll — Discard the top five cards of your reserve.\u003cbr\u003e\nSearch the cards discarded to this spell for two cards and add them to your hand. Take 1 damage.",
      "0",
      "R",
    ],
    [
      "Flash Freeze",
      "C:\\Card Stuff\\Schooless.jpg",
      "Hex Evocation",
      "1",
      "2",
      "Deal 1 damage to any target. If a spell is damaged this way, Instill freeze covering it. (Your opponent makes the token.)",
      "1",
      "C",
    ],
    [
      "Floodgate",
      "C:\\Card Stuff\\Schooless.jpg",
      "Rite",
      "2",
      "5",
      "Ritual 5 (Create a ritual with five of your spells in play.)\u003cbr\u003e\nAt the start of your turn, if the ritual is intact, place a flood counter on Floodgate, then break every spell in play with stability less than the number of counters on it, except for the ones in the ritual.",
      "3",
      "U",
    ],
    [
      "Forget Me Knot",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral Enchantment",
      "3",
      "3",
      "Break up to three of your spells.",
      "0",
      "C",
    ],
    [
      "Guidance",
      "C:\\Card Stuff\\Schooless.jpg",
      "Enchantment",
      "3",
      "4",
      "Look at the top 4 cards of your deck or reserve. You may put them back on the top or bottom of that zone in any order.",
      "1",
      "U",
    ],
    [
      "Lightning Bolt",
      "C:\\Card Stuff\\Schooless.jpg",
      "Evocation",
      "1",
      "2",
      "Deal 3 damage to any target.",
      "1",
      "C",
    ],
    [
      "Mage Armor",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral  Abjuration",
      "2",
      "5",
      "Make a shield token. Place the top card of your deck under that token. When that token leaves play, add the card under it to your hand.",
      "0",
      "U",
    ],
    [
      "Messenger",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral Transmutation",
      "2",
      "2",
      "Swift\u003cbr\u003e\nShuffle one of your summons to your reserve, then draw a card from your reserve.",
      "0",
      "C",
    ],
    [
      "Minimus Containment",
      "C:\\Card Stuff\\Schooless.jpg",
      "Curse",
      "1",
      "4",
      "Attach Minimus Containment to target spell.\u003cbr\u003e\nAs long as Minimus Containment is attached, the attached spell loses all text and gains 4 pitch value.",
      "2",
      "U",
    ],
    [
      "Modify Memory",
      "C:\\Card Stuff\\Schooless.jpg",
      "Enchantment",
      "2",
      "2",
      "Search your opponent's hand for a card, then put that card on the bottom of their deck face down.",
      "1",
      "C",
    ],
    [
      "Parry",
      "C:\\Card Stuff\\Schooless.jpg",
      "Abjuration",
      "2",
      "3",
      "Swift \u003cbr\u003e\nTarget spell deals no damage this turn.",
      "1",
      "C",
    ],
    [
      "Pinprick",
      "C:\\Card Stuff\\Schooless.jpg",
      "Evocation",
      "2",
      "0",
      "Deal 1 damage to target spell.",
      "1",
      "C",
    ],
    [
      "Prestidigitation",
      "C:\\Card Stuff\\Schooless.jpg",
      "Transmutation",
      "0",
      "0",
      "When you pitch Prestidigitation, draw a card.",
      "1",
      "C",
    ],
    [
      "Quake",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral",
      "2",
      "5",
      "Swift\u003cbr\u003e\nDeal 2 damage to each spell.",
      "0",
      "U",
    ],
    [
      "Recall",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral",
      "2",
      "4",
      "Swift\u003cbr\u003e\nReturn up to two of your spells to your hand.",
      "0",
      "U",
    ],
    [
      "Reparations",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral",
      "2",
      "1",
      "Swift\u003cbr\u003e\nBreak target spell. The opponent gains 1 life.",
      "0",
      "C",
    ],
    [
      "Resculpt",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral",
      "1",
      "2",
      "Toll — Discard a card.\u003cbr\u003e\nSearch your reserve for a card that shares a type with the discarded card and add it to your hand.",
      "0",
      "C",
    ],
    [
      "Sanctuary",
      "C:\\Card Stuff\\Schooless.jpg",
      "Place",
      "2",
      "2",
      "As long as Sanctuary is in play, you can't be the target of your opponent's spells.\nAt the beginning of your turn, break Sanctuary.",
      "2",
      "C",
    ],
    [
      "Scheme",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral",
      "2",
      "3",
      "Search the top 3 cards of your reserve for a card and add it to your hand.",
      "0",
      "C",
    ],
    [
      "Serendipity",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral Enchantment",
      "2",
      "4",
      "Shuffle your hand into your reserve, then draw that many cards from it.",
      "0",
      "U",
    ],
    [
      "Shatter",
      "C:\\Card Stuff\\Schooless.jpg",
      "Evocation",
      "2",
      "4",
      "Deal 5 damage to target spell.",
      "1",
      "U",
    ],
    [
      "Song of the Frost Painter",
      "C:\\Card Stuff\\Schooless.jpg",
      "Enchantment",
      "2",
      "1",
      "You may search your deck for any number of Hymns and put them into play. Make a freeze token covering each of them.",
      "1",
      "U",
    ],
    [
      "Spectral Form",
      "C:\\Card Stuff\\Schooless.jpg",
      "Form",
      "2",
      "3",
      "Swift\u003cbr\u003e\nWhenever you would take damage, you can pitch a card with the value of damage you would take or more to prevent it.",
      "2",
      "C",
    ],
    [
      "Sunder",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral Transmutation",
      "1",
      "6",
      "Reduce the stability of all your opponent's spells by 4. Move to the draw step.",
      "0",
      "R",
    ],
    [
      "Tarot's Wisdom",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral",
      "0",
      "0",
      "Reveal the top card of each deck and reserve.",
      "0",
      "C",
    ],
    [
      "Turn to Flame",
      "C:\\Card Stuff\\Schooless.jpg",
      "Hex",
      "2",
      "5",
      "Break target spell. Instill burn. (Your opponent makes the token.)",
      "2",
      "U",
    ],
    [
      "Unwind",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral",
      "2",
      "0",
      "Return one of your spells to your hand.",
      "0",
      "C",
    ],
    [
      "Wall of Magma",
      "C:\\Card Stuff\\Schooless.jpg",
      "Abjuration",
      "2",
      "5",
      "Aegis\u003cbr\u003e\nWhenever this spell is damaged, each player makes a burn token.",
      "4",
      "U",
    ],
    [
      "Whiteout",
      "C:\\Card Stuff\\Schooless.jpg",
      "Ephemeral Hex",
      "2",
      "4",
      "Instill freeze covering target card. Draw a card. (Your opponent makes the token.)",
      "0",
      "U",
    ],
    [
      "Wind Wall",
      "C:\\Card Stuff\\Schooless.jpg",
      "Abjuration",
      "2",
      "3",
      "Aegis, Feedback (If this spell takes excess damage, the excess is dealt to you.)",
      "3",
      "C",
    ],
  ],
};
